Microsoft_WebSite/Models/ErrorViewModel.cs
namespace Microsoft_WebSite.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Microsoft_WebSite/Areas/Admin/Controllers/AboutUsController.cs
using Microsoft_WebSite.DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using MicrosoftWebSite.Business.Interfaces;

namespace Microsoft_WebSite.Areas.Admin.Controllers;

[Authorize(Roles = "Admin")]
[Area("Admin")]
public class AboutUsController : Controller
{
    private IAboutUsService _aboutUsService;
    
    
    public AboutUsController(IAboutUsService aboutUsService)
    {
        _aboutUsService = aboutUsService;
    }

    
    public IActionResult Index()
    {
        var aboutUsData = _aboutUsService.getAboutUs();
        
        return View(aboutUsData);
    }


    [HttpPost]
    public IActionResult updateAboutUs(AboutUs aboutUs)
    {
        
        if (_aboutUsService.updateAboutus(aboutUs))
        {
            return RedirectToAction("Index");
        }

        return BadRequest();
    }
    
}

Microsoft_WebSite/Areas/Admin/Controllers/AuthController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MicrosoftWebSite.Business.Dtos;
using MicrosoftWebSite.Business.Interfaces;

namespace Microsoft_WebSite.Areas.Admin.Controllers;


[Area("Admin")]
public class AuthController : Controller
{
    IAuthService _authService;

    public AuthController(IAuthService authService)
    {
        _authService = authService;
    }

    public IActionResult SignIn(LoginDto loginDto)
    {
        if (Request.Method == "GET")
        {
            return View();
        }
        else
        {
            if (loginDto != null)
            {
                var founded_user = _authService.SignIn(loginDto);
                
                if (founded_user != null)
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name,loginDto.userName),
                        new Claim(ClaimTypes.Role,founded_user.userRole)
                    };
                    
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    var authProp = new AuthenticationProperties
                    {
                         IsPersistent = true,
                         ExpiresUtc = DateTime.UtcNow.AddMinutes(1),
                    };

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProp);

                    HttpContext.Session.SetString("userName", founded_user.UserUsername);
                  

                    return RedirectToAction("Index", "Dashboard");
                }
                
                
                
                
                
            }
        }

        return null;
    }
    
    public IActionResult SignOut()
    {
        return null;
    }
    
    public IActionResult SignUp()
    {
        return View();
    }

    public IActionResult AccessDenied()
    {
        return View();
    }
    
}

Microsoft_WebSite/Areas/Admin/Controllers/DashboardController.cs
using Microsoft_WebSite.DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Microsoft_WebSite.Areas.Admin.Controllers;


[Authorize(Roles = "Admin")]
[Area("Admin")]
public class DashboardController : Controller
{
    // GET
    public IActionResult Index()
    {
      
        return View();
    }
}

Microsoft_WebSite/Areas/Admin/Controllers/PricingController.cs
using Microsoft_WebSite.DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MicrosoftWebSite.Business.Interfaces;

namespace Microsoft_WebSite.Areas.Admin.Controllers;

[Authorize(Roles = "Admin")]
[Area("Admin")]
public class PricingController : Controller
{
    IPricingService _pricingService;


    public PricingController(IPricingService pricingService)
    {
        _pricingService = pricingService;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult PricingDetails(string productTitle)
    {
        var route_Value = HttpContext.Request.RouteValues;
        ViewBag.PackageProductUnitTitle = productTitle;
        ViewBag.AreaName = route_Value["area"].ToString();
        ViewBag.ControllerName = route_Value["controller"].ToString();
        ViewBag.ActionName = route_Value["action"].ToString();
        
       
        
        var product_units = _pricingService.getAllPackageProductUnits(productTitle);

        return View(product_units);
    }

    [HttpPost]
    public IActionResult PrcingDetailsUpdate(PackageProductUnit packageProductUnit)
    {
      
       
        
        _pricingService.updatePackageProductUnit(packageProductUnit);
        
        return RedirectToAction("PricingDetails", new { productTitle = packageProductUnit.PackageProductUnitTitle });
        
        
    }
    
}

Microsoft_WebSite/Areas/Admin/Controllers/ServicesController.cs
using Microsoft_WebSite.DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MicrosoftWebSite.Business.Interfaces;


namespace Microsoft_WebSite.Areas.Admin.Controllers;

[Authorize(Roles = "Admin")]
[Area("Admin")]
public class ServicesController : Controller
{
    
    IOurServiceService _services;
    
    public ServicesController(IOurServiceService services)
    {
        _services = services;
    }

    public IActionResult Index()
    {
        var services = _services.getServices();
        return View(services);
    }
    
    [HttpGet]
    public IActionResult ServiceDetail(int id)
    {
        var service = _services.getServiceById(id);
        return View(service);
    }
    
    [HttpPost]
    public IActionResult ServiceDetailUpdate(Service service)
    {
        _services.updateService(service);
        return RedirectToAction("Index");
    
    }
}

Microsoft_WebSite/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using MicrosoftWebSite.Business.Interfaces;

namespace Microsoft_WebSite.Controllers;

public class ContactController : Controller
{
    IAboutUsService _aboutUsService;

    public ContactController(IAboutUsService aboutUsService)
    {
        _aboutUsService = aboutUsService;
    }
    
    // GET
    public IActionResult Index()
    {
        var aboutUs = _aboutUsService.getAboutUs();
        
        return View();
    }
}

Microsoft_WebSite/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Microsoft_WebSite.Controllers;

public class ErrorController : Controller
{
    [Route("{statusCode}")]
    public IActionResult ErrorPages(int statusCode)
    {
        
        return View();
    }
}

Microsoft_WebSite/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft_WebSite.Models;
using MicrosoftWebSite.Business.Dtos;
using MicrosoftWebSite.Business.Interfaces;

namespace Microsoft_WebSite.Controllers;

public class HomeController : Controller
{
  IHomeService _homeService;
  public HomeController(IHomeService homeService)
  {
    _homeService = homeService;
  }
  
  public IActionResult Index()
  {

    HomeDto homeData = _homeService.getHomeInfo();
      
    
    return View(homeData);
  }
  
  public IActionResult Error()
  {
    
    return View();
  }


  
  
}

Microsoft_WebSite/ViewComponent/ServiceViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MicrosoftWebSite.Business.Interfaces;

namespace Microsoft_WebSite.ViewComponent;

public class ServiceViewComponent:Microsoft.AspNetCore.Mvc.ViewComponent
{
    private IOurServiceService _ourServiceService;
    
    public ServiceViewComponent(IOurServiceService ourServiceService)
    {
        _ourServiceService = ourServiceService;
    }
    
    
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var services = _ourServiceService.getServices();
        return View(services);
    }
}

Microsoft_WebSite/Areas/Admin/Views/AboutUs/Index.cshtml
@using Microsoft_WebSite.DataAccess.Entities
@model AboutUs
@{
    Layout = "_AdminLayout";
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>

    
    
        <h1 style="padding-top: 20px">BURASI ABOUT US SAYFASI</h1>
        <form action="/admin/AboutUs/updateAboutUs" method="post">
            <div class="mb-3">
                <input type="text" class="form-control" name="AboutUsID" value="@Model.AboutUsID" hidden>
                <label for="exampleFormControlInput1" class="form-label">Title</label>
                <input type="text" class="form-control" name="AboutUsTitle" value="@Model.AboutUsTitle">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Açıklama</label>
                <textarea class="form-control" aria-label="With textarea" name="AboutUsContent" >@Model.AboutUsContent</textarea>
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-success">Success</button>
            </div>
        </form>
   

</body>
</html>

Microsoft_WebSite/Areas/Admin/Views/Dashboard/Index.cshtml
@model Microsoft_WebSite.DataAccess.Entities.User
@{
    Layout = "_AdminLayout";
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
    <h1 style="padding-top: 20px">
        
        
    </h1>
</div>
</body>
</html>

Microsoft_WebSite/Areas/Admin/Views/Pricing/Index.cshtml
@{
    Layout = "_AdminLayout";
}

<table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Product Title</th>
        <th scope="col">Detail</th>
        
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">1</th>
        <th scope="row">users included</th>
        <td><a href=@Url.Action("PricingDetails","Pricing",new {area="Admin",productTitle="users included"}) class="btn btn-warning">Detail</a></td>
    </tr>
    <tr>
        <th scope="row">1</th>
        <th scope="row">GB of storage</th>
        <td><a href=@Url.Action("PricingDetails","Pricing",new {area="Admin",productTitle="GB of storage"}) class="btn btn-warning">Detail</a></td>
    </tr>
    <tr>
        <th scope="row">1</th>
        <th scope="row">sms</th>
        <td><a href=@Url.Action("PricingDetails","Pricing",new {area="Admin",productTitle="sms"}) class="btn btn-warning">Detail</a></td>
    </tr>
    <tr>
        <th scope="row">1</th>
        <th scope="row">Web Site Design</th>
        <td><a href=@Url.Action("PricingDetails","Pricing",new {area="Admin",productTitle="Web Site Design"}) class="btn btn-warning">Detail</a></td>
    </tr>
    <tr>
        <th scope="row">1</th>
        <th scope="row">Email</th>
        <td><a href=@Url.Action("PricingDetails","Pricing",new {area="Admin",productTitle="Email"}) class="btn btn-warning">Detail</a></td>
    </tr>


    </tbody>
</table>

Microsoft_WebSite/Areas/Admin/Views/Pricing/PricingDetails.cshtml
@using Microsoft_WebSite.DataAccess.Entities
@model List<PackageProductUnit>
@{
    Layout = "_AdminLayout";
}

<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">@ViewBag.PackageProductUnitTitle</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">@ViewBag.AreaName</a></li>
                        <li class="breadcrumb-item"><a href="#">@ViewBag.ControllerName</a></li>
                        <li class="breadcrumb-item active">@ViewBag.ActionName</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Content</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Save</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <form action="/admin/pricing/PrcingDetailsUpdate" method="post">
                <input name="PackageProductUnitTitle" value="@item.PackageProductUnitTitle" hidden/>
                <tr>
                    <th scope="row">
                        @item.PackageProductUnitID
                        <input name="PackageProductUnitID" value="@item.PackageProductUnitID" hidden/>
                    </th>
                    <td><input type="text" class="form-control" name="PackageProductUnitContent" value="@item.PackageProductUnitContent"></td>
                    <td> <input type="text" class="form-control" name="PackageProductUnitPrice" value="@item.PackageProductUnitPrice"></td>
                    <td> <button class="btn btn-success">Save</button></td>
                </tr>
            </form>

        }

        </tbody>
    </table>
</div>

Microsoft_WebSite/Areas/Admin/Views/Services/Index.cshtml
@using Microsoft_WebSite.DataAccess.Entities
@model List<Service>
@{
    Layout = "_AdminLayout";
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
    <h1>BURASI SERVICES SAYFASI</h1>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Service Title</th>
            <th>Service Content</th>
            <th>Service ImagePath</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        
            @foreach (var item in Model)
            {
                <tr>
                <td>@item.ServiceId</td>
                <td>@item.ServiceTitle</td>
                <td>@item.ServiceContent</td>
                <td>@item.ServiceImagePath</td>
                <td><a class="btn btn-warning" href="/admin/services/ServiceDetail/@item.ServiceId">Update</a></td>
                <td><a class="btn btn-danger">Delete</a></td>
                </tr>
            }
        
        </tbody>
    </table>
</div>
</body>
</html>

Microsoft_WebSite/Areas/Admin/Views/Services/ServiceDetail.cshtml
@using Microsoft_WebSite.DataAccess.Entities
@model Service

@{
    Layout = "_AdminLayout";
}

    <form action="/admin/services/ServiceDetailUpdate" method="post">
    
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">ID</label>
            <input type="text" class="form-control" name="ServiceId" value=@Model.ServiceId>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Service Title</label>
            <input type="text" class="form-control" name="ServiceTitle" value=@Model.ServiceTitle>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Service Content</label>
            <input type="text" class="form-control" name="ServiceContent" value="@Model.ServiceContent">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Service ImagePath</label>
            <input type="text" class="form-control" name="ServiceImagePath" value="@Model.ServiceImagePath">
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-warning">GÜNCELLE</button>
        </div>
    
    </form>

Microsoft_WebSite/Views/Contact/Index.cshtml
<h2 style="text-align: center;margin-top: 30px">BİZİMLE İLETİŞİME GEÇİN</h2>

<div style="width: 100%;display: flex;justify-content: center;align-items: center;flex-direction: column;margin-top: 30px">
    <div class="mb-3" style="width: 30%">
        <label for="exampleFormControlInput1" class="form-label">Email address</label>
        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
    </div>
    <div class="mb-3" style="width: 30%">
        <label for="exampleFormControlTextarea1" class="form-label">Açıklama</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
</div>

Microsoft_WebSite/Views/Home/Index.cshtml
@using System.Drawing
@using Microsoft_WebSite.DataAccess.Entities
@model MicrosoftWebSite.Business.Dtos.HomeDto
@{
  string proPlanDesign = "card mb-4 rounded-3 shadow-sm border-primary";
  string freePlanDesign = "card mb-4 rounded-3 shadow-sm";
  
  @functions{

    public double PriceSum(List<PackageProductUnit> productUnits)
    {
      var initialPrice = 0;
      foreach (var item in productUnits)
      {
        initialPrice += Convert.ToInt32(item.PackageProductUnitPrice);
      }

      return initialPrice+initialPrice*0.18;
    }

  }
  }
<!--HERO-START-->

  <div id="hero">
    @await Html.PartialAsync("_Hero")
  </div>

<!--HERO-END-->
<!--Features START-->
@await Html.PartialAsync("_Features")
<!--Features END-->
    <!--ABOUT-US-START-->
    @await Html.PartialAsync("_AboutUs",Model.aboutUs)
    
    <!--ABOUT-US-END-->
     <!--SERVİCES-START-->
    @await Component.InvokeAsync("Service")
    <!--SERVİCES-END-->
    <!--PRICING-START-->
    <div class="container py-3" id="pricing">
        <main>
          <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            @foreach (var packageItem in Model.Package)
            {
              <div class="col">
                <div class="@(packageItem.PackageTitle == "Enterprise" ? proPlanDesign : freePlanDesign)" >
                  <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">@packageItem.PackageTitle</h4>
                   
                  </div>
                  <div class="card-body">
                    
                    <h1 class="card-title pricing-card-title">$@PriceSum(packageItem.PackageProductUnits)<small class="text-body-secondary fw-light">/mo</small></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                      @foreach (var packageProductUnitItem in packageItem.PackageProductUnits)
                      {
                        <li>@packageProductUnitItem.PackageProductUnitContent</li>
                      }

                    </ul>
                    <button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
                  </div>
                </div>
              </div>
            }
           
          </div>
        </main>
   
      </div>
    <!--PRICING-END-->

Microsoft_WebSite/Views/Shared/Components/Service/Default.cshtml
@using Microsoft_WebSite.DataAccess.Entities
@model List<Service>
<div class="container px-4 py-5" id="custom-cards">
    <h2 class="pb-2 border-bottom">Services</h2>

    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
      @foreach (var item in Model)
      {
          <div class="col">
              <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('@item.ServiceImagePath');background-repeat: no-repeat">
                  <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                      <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">@item.ServiceTitle</h3>
                      <ul class="d-flex list-unstyled mt-auto">
                          <li class="me-auto">
                              <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
                          </li>
                          <li class="d-flex align-items-center me-3">
                              <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                              <small>Earth</small>
                          </li>
                          <li class="d-flex align-items-center">
                              <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"></use></svg>
                              <small>3d</small>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
      }
   


    </div>
  </div>

Microsoft_WebSite/Views/Shared/_AboutUs.cshtml
@using Microsoft_WebSite.DataAccess.Entities
@model AboutUs
<div class="container my-5" id="about">
    <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
            <h1 class="display-4 fw-bold lh-1 text-body-emphasis">@Model.AboutUsTitle</h1>
            <p class="lead">@Model.AboutUsContent</p>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                <button type="button" class="btn btn-primary btn-lg px-4 me-md-2 fw-bold">Primary</button>
                <button type="button" class="btn btn-outline-secondary btn-lg px-4">Default</button>
            </div>
        </div>
        <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
            <img class="rounded-lg-3" src="https://nairametrics.com/wp-content/uploads/2024/05/Microsoft-Corporation.jpg" alt="" width="720" style="">
        </div>
    </div>
</div>

Microsoft_WebSite/Views/Shared/_Features.cshtml
  <div class="container marketing">

    <!-- Three columns of text below the carousel -->



    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">First featurette heading. <span class="text-body-secondary">It’ll blow your mind.</span></h2>
        <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">Oh yeah, it’s that good. <span class="text-body-secondary">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">And lastly, this one. <span class="text-body-secondary">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div>

Microsoft_WebSite/Views/Shared/_Header.cshtml
<head><script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Checkout example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/checkout/">



   

    <link href="/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">





    <!-- Custom styles for this template -->
    <link href="checkout.css" rel="stylesheet">
</head>
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <div class="col-md-3 mb-2 mb-md-0">
            <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
                <img src="https://upload.wikimedia.org/wikipedia/commons/archive/9/96/20210729021035%21Microsoft_logo_%282012%29.svg"/>
            </a>
        </div>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="#" class="nav-link px-2 link-secondary">Home</a></li>
            <li><a href="#" class="nav-link px-2">Features</a></li>
            <li><a href="#pricing" class="nav-link px-2">Pricing</a></li>
            <li><a href="#" class="nav-link px-2">FAQs</a></li>
            <li><a href="#about" class="nav-link px-2">About</a></li>
        </ul>

        <div class="col-md-3 text-end">
            <a  class="btn btn-outline-primary me-2" href="/admin/auth/SignIn">Sign-In</a>
            <a  class="btn btn-primary" href="/admin/auth/SignUp">Sign-up</a>
        </div>
    </header>
</div>